#!/bin/sh
set -eu

REPOROOT="$PWD"
while [ "$REPOROOT" != '/' ]; do
    [ -d "$REPOROOT/.git" ] && break
    REPOROOT=$(dirname "$REPOROOT")
done
[ "$REPOROOT" != '/' ] || exit 1

write_thing() {
    name=$1
    shift
    value="$*"

    mkdir -p "$REPOROOT/.git/refs/gitstore"
    hashed_value=$(echo "$value" | git hash-object -w --stdin)
    hashed_stage=$(git update-index --add --cacheinfo "100644,$hashed_value,$name")
    hashed_tree=$(git write-tree "$hashed_stage")
    if [ -d "$REPOROOT/.git/refs/gitstore/store" ]; then
        hashed_commit=$(git commit-tree "$hashed_tree" -m update -p "$(cat "$REPOROOT/.git/refs/gitstore/store")")
        git update-ref refs/gitstore/store "$hashed_commit"
    else
        hashed_commit=$(git commit-tree "$hashed_tree" -m update)
        echo "$hashed_commit" >"$REPOROOT/.git/refs/gitstore/store"
    fi

}

read_thing() {
    name=$1
    git show "refs/gitstore/store:$name"
}

route() {
    cmd=${1:-}
    [ -z "$1" ] || shift
    case "$cmd" in
    write)
        write_thing "$@"
        ;;
    read)
        read_thing "$@"
        ;;
    push)
	    git push "${1:-}" 'refs/gitstore/*'
        ;;
    pull)
	    git fetch "${1:-}"  'refs/gitstore/*:refs/gitstore/*'
	    ;;
    *)
        echo "IDK WTF dis means: $cmd $*"
    esac
}


route "$@"
